# Generated by Django 5.1 on 2024-08-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='created_at',
            new_name='date_added',
        ),
    ]
